name: Run tests
author: Jesús Leganés-Combarro 'piranna' (http://piranna.github.io/)
description: Detect and run tests, for Jest, Node.js `test`, or build by default

runs:
  using: composite
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: bin.sh
      shell: bash
      env:
        FORCE_COLOR: '1'

branding:
  color: orange
  icon: list
